### ISSUE TITLE
Update our examples to set a default provider

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/nulecule-library#65]
To educate our audience that they can set a default provider in the Nulecule itself we should update our examples to set this. The way to do this is like so:

```
---                                                                                                                                                      
specversion: 0.0.2
id: mariadb-atomicapp
params:
    - name: provider
      description: The provider that is used to deploy the application
      default: openshift
...
```

We should make them default to kubernetes as long as they support kubernetes. But the examples will at least show users they are capable of setting a default other than kubernetes.
